CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Organizations" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "Domain" character varying(100) NOT NULL,
    "TimeZone" character varying(10) DEFAULT 'UTC',
    "Currency" character varying(5) DEFAULT 'USD',
    "IsActive" boolean NOT NULL,
    "SubscriptionExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CreatedBy" text,
    "UpdatedBy" text,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "BusinessUsers" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PhoneNumber" character varying(20),
    "JobTitle" character varying(100),
    "IsActive" boolean NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "IdentityUserId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CreatedBy" text,
    "UpdatedBy" text,
    "OrganizationId" uuid NOT NULL,
    CONSTRAINT "PK_BusinessUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BusinessUsers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Stages" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Order" integer NOT NULL,
    "Color" character varying(7) NOT NULL DEFAULT '#3B82F6',
    "IsActive" boolean NOT NULL,
    "IsWonStage" boolean NOT NULL,
    "IsLostStage" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CreatedBy" text,
    "UpdatedBy" text,
    "OrganizationId" uuid NOT NULL,
    CONSTRAINT "PK_Stages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stages_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "OrganizationId" uuid,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id")
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Leads" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "FirstName" character varying(100),
    "LastName" character varying(100),
    "Email" character varying(255),
    "PhoneNumber" character varying(20),
    "Company" character varying(200),
    "JobTitle" character varying(100),
    "EstimatedValue" numeric(18,2),
    "Probability" integer NOT NULL,
    "ExpectedCloseDate" timestamp with time zone,
    "Notes" character varying(2000),
    "Source" character varying(50),
    "Status" character varying(20) NOT NULL DEFAULT 'Open',
    "LastContactedAt" timestamp with time zone,
    "StageId" uuid NOT NULL,
    "AssignedUserId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CreatedBy" text,
    "UpdatedBy" text,
    "OrganizationId" uuid NOT NULL,
    CONSTRAINT "PK_Leads" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Leads_BusinessUsers_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "BusinessUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Leads_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Leads_Stages_StageId" FOREIGN KEY ("StageId") REFERENCES "Stages" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tasks" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000),
    "Type" character varying(20) NOT NULL DEFAULT 'Call',
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "DueDate" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "Priority" character varying(20) NOT NULL DEFAULT 'Medium',
    "Notes" character varying(1000),
    "DurationMinutes" integer,
    "LeadId" uuid,
    "AssignedUserId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CreatedBy" text,
    "UpdatedBy" text,
    "OrganizationId" uuid NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_BusinessUsers_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "BusinessUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Tasks_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tasks_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_BusinessUsers_CreatedAt" ON "BusinessUsers" ("CreatedAt");

CREATE INDEX "IX_BusinessUsers_OrganizationId" ON "BusinessUsers" ("OrganizationId");

CREATE UNIQUE INDEX "IX_BusinessUsers_OrganizationId_Email" ON "BusinessUsers" ("OrganizationId", "Email");

CREATE INDEX "IX_Leads_AssignedUserId" ON "Leads" ("AssignedUserId");

CREATE INDEX "IX_Leads_CreatedAt" ON "Leads" ("CreatedAt");

CREATE INDEX "IX_Leads_Email" ON "Leads" ("Email");

CREATE INDEX "IX_Leads_LastContactedAt" ON "Leads" ("LastContactedAt");

CREATE INDEX "IX_Leads_OrganizationId" ON "Leads" ("OrganizationId");

CREATE INDEX "IX_Leads_StageId" ON "Leads" ("StageId");

CREATE INDEX "IX_Organizations_CreatedAt" ON "Organizations" ("CreatedAt");

CREATE UNIQUE INDEX "IX_Organizations_Domain" ON "Organizations" ("Domain");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_Stages_OrganizationId" ON "Stages" ("OrganizationId");

CREATE UNIQUE INDEX "IX_Stages_OrganizationId_Order" ON "Stages" ("OrganizationId", "Order");

CREATE INDEX "IX_Tasks_AssignedUserId" ON "Tasks" ("AssignedUserId");

CREATE INDEX "IX_Tasks_CreatedAt" ON "Tasks" ("CreatedAt");

CREATE INDEX "IX_Tasks_DueDate" ON "Tasks" ("DueDate");

CREATE INDEX "IX_Tasks_LeadId" ON "Tasks" ("LeadId");

CREATE INDEX "IX_Tasks_OrganizationId" ON "Tasks" ("OrganizationId");

CREATE INDEX "IX_Tasks_Status" ON "Tasks" ("Status");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_Users_OrganizationId_Email" ON "Users" ("OrganizationId", "Email");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250906052609_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" DROP CONSTRAINT "FK_Users_Organizations_OrganizationId";

ALTER TABLE "Users" ALTER COLUMN "UpdatedAt" SET DEFAULT (CURRENT_TIMESTAMP);

UPDATE "Users" SET "OrganizationId" = '00000000-0000-0000-0000-000000000000' WHERE "OrganizationId" IS NULL;
ALTER TABLE "Users" ALTER COLUMN "OrganizationId" SET NOT NULL;
ALTER TABLE "Users" ALTER COLUMN "OrganizationId" SET DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Users" ADD "DomainUserId" uuid;

ALTER TABLE "Users" ADD "JobTitle" character varying(100);

ALTER TABLE "Users" ADD "LastLoginAt" timestamp with time zone;

CREATE INDEX "IX_Users_CreatedAt" ON "Users" ("CreatedAt");

CREATE UNIQUE INDEX "IX_Users_DomainUserId" ON "Users" ("DomainUserId");

CREATE INDEX "IX_Users_OrganizationId" ON "Users" ("OrganizationId");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_BusinessUsers_DomainUserId" FOREIGN KEY ("DomainUserId") REFERENCES "BusinessUsers" ("Id") ON DELETE SET NULL;

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250907001901_AddApplicationUserFields', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Organizations" ALTER COLUMN "TimeZone" TYPE character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250907002634_FixTimeZoneLength', '8.0.0');

COMMIT;

